=== hms-dbmi/vitessce/src/schemas/cell_sets_tabular.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/hubmapconsortium/vitessce/#cell_sets_tabular",
    "title": "Vitessce cell sets data, tabular format",
    "definitions": {
        "colorArray": {
            "type": "array",
            "items": { "type": "integer", "minimum": 0, "maximum": 255 },
            "minItems": 3,
            "maxItems": 3
        }
    },
    "type": "array",
    "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["group_name", "set_name", "cell_id"],
        "properties": {
            "group_name": { "type": "string" },
            "set_name": { "type": "string" },
            "set_color": { "$ref": "#/definitions/colorArray" },
            "cell_id": { "type": "string" }
        }
    }
}

=== hms-dbmi/vitessce/src/schemas/fixtures/cell-sets-tabular.good.json
[
    {
        "group_name": "Clustering Algorithm",
        "set_name": "Cluster A",
        "set_color": [255, 0, 0],
        "cell_id": "cell_243"
    },
    {
        "group_name": "Clustering Algorithm",
        "set_name": "Cluster A",
        "set_color": [255, 0, 0],
        "cell_id": "cell_271"
    },
    {
        "group_name": "Clustering Algorithm",
        "set_name": "Cluster A",
        "set_color": [255, 0, 0],
        "cell_id": "cell_247"
    },
    {
        "group_name": "Clustering Algorithm",
        "set_name": "Cluster A",
        "set_color": [255, 0, 0],
        "cell_id": "cell_248"
    }
]
