=== hms-dbmi/vitessce/src/schemas/hierarchical-sets.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/hubmapconsortium/vitessce/#hierarchical-sets",
    "title": "Vitessce hierarchical sets data",
    "type": "object",
    "definitions": {
      "stringArray": {
        "type": "array",
        "items": { "type": "string" }
      },
      "colorArray": {
          "type": "array",
          "items": { "type": "integer", "minimum": 0, "maximum": 255 },
          "minItems": 3,
          "maxItems": 3
      }
    },
    "additionalProperties": false,
    "required": ["datasetId", "version", "setsType", "setsTree"],
    "properties": {
      "datasetId": { "type": "string" },
      "version": { "type": "string" },
      "setsType": { "type": "string" },
      "setsTree": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": ["key", "name"],
            "properties": {
              "key": { "type": "string" },
              "name": { "type": "string" },
              "color": { "$ref": "#/definitions/colorArray" },
              "set": { "$ref": "#/definitions/stringArray" }
            }
          }
        }
    }
  }

=== hms-dbmi/vitessce/src/schemas/fixtures/hierarchical-sets.good.json
{
    "datasetId":"linnarsson-2018",
    "version":"0.0.20",
	"setsType":"cell",
	"setsTree":[
		{"key":"factors","name":"Factors"},
		{"key":"factors\tvasculature","name":"Vasculature"},
		{"key":"factors\tvasculature\tvascular-smooth-muscle","name":"Vascular Smooth Muscle","set":["85","260"]},
		{"key":"factors\tvasculature\tendothelial","name":"Endothelial","color":[128,128,255],"set":["15","19","21","25"]}
	]
}
